apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customrouter-external-processor
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: customrouter-external-processor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: customrouter-external-processor
subjects:
  - kind: ServiceAccount
    name: customrouter-external-processor
    namespace: default
