apiVersion: v1
kind: Service
metadata:
  name: customrouter-external-processor
  labels:
    app.kubernetes.io/name: customrouter-external-processor
    app.kubernetes.io/component: external-processor
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9001
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: customrouter-external-processor
