apiVersion: v1
kind: ServiceAccount
metadata:
  name: customrouter-external-processor
  labels:
    app.kubernetes.io/name: customrouter-external-processor
    app.kubernetes.io/component: external-processor
