apiVersion: v2
name: customrouter
description: A Helm chart for CustomRouter - Kubernetes operator and external processor for dynamic HTTP routing
type: application
version: 0.3.3
appVersion: "0.3.3"
keywords:
  - kubernetes
  - operator
  - envoy
  - istio
  - routing
  - ext_proc
maintainers:
  - name: Freepik Company
home: https://github.com/freepik-company/customrouter
sources:
  - https://github.com/freepik-company/customrouter
