{{- if and .Values.operator.enabled .Values.operator.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "customrouter.operator.name" . }}
  labels:
    {{- include "customrouter.operator.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "customrouter.operator.name" . }}
  minReplicas: {{ .Values.operator.hpa.minReplicas }}
  maxReplicas: {{ .Values.operator.hpa.maxReplicas }}
  {{- with .Values.operator.hpa.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.operator.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
