# This rule is not used by the project customrouter itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the customrouter.freepik.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: customrouter
    app.kubernetes.io/managed-by: kustomize
  name: customhttproute-editor-role
rules:
- apiGroups:
  - customrouter.freepik.com
  resources:
  - customhttproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customrouter.freepik.com
  resources:
  - customhttproutes/status
  verbs:
  - get
