# This rule is not used by the project customrouter itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over customrouter.freepik.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: customrouter
    app.kubernetes.io/managed-by: kustomize
  name: externalprocessorattachment-admin-role
rules:
- apiGroups:
  - customrouter.freepik.com
  resources:
  - externalprocessorattachments
  verbs:
  - '*'
- apiGroups:
  - customrouter.freepik.com
  resources:
  - externalprocessorattachments/status
  verbs:
  - get
