# This rule is not used by the project customrouter itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to customrouter.freepik.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: customrouter
    app.kubernetes.io/managed-by: kustomize
  name: externalprocessorattachment-viewer-role
rules:
- apiGroups:
  - customrouter.freepik.com
  resources:
  - externalprocessorattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - customrouter.freepik.com
  resources:
  - externalprocessorattachments/status
  verbs:
  - get
